### ISSUE TITLE
Latest release

### ISSUE THREAD

**Issue by FlorianLeChat** [danielga/gm_cvarsx#2]
The latest release is now **4 years old** and doesn't include the fix (https://github.com/danielga/gm_cvarsx/commit/53a4099b1f0b6f4f322fcd3c6a8f92cb46a7d56d) you brought to the function for removing convars ([gm_concommandx](https://github.com/danielga/gm_concommandx) is also affected by the same issue). Here is the error using your latest compiled version:

![image](https://user-images.githubusercontent.com/26360935/152637203-3af3e6c1-4cc5-4473-9054-0e18c18fb715.png)
![image](https://user-images.githubusercontent.com/26360935/152637191-9bf5f624-a37a-42f0-aa48-f2484b9ee2f7.png)

Despite everything I managed to compile your code for Windows (Gmod 32-bit branch) and I can confirm that the bug is well fixed with your changes. However, I would like to use the module on my server using Linux (Debian 11), I managed to compile it but when adding it to the server, I always get this error:

![image](https://user-images.githubusercontent.com/26360935/152637952-99d1cda6-a4e2-4116-894e-eaaeac19fd20.png)

Anyway, it would be really nice if you could add the latest binaries because honestly the whole thing works perfectly fine 👍

**Comment by danielga** [comment]
Latest build should show up [here](https://github.com/danielga/gm_cvarsx/releases/tag/r1).

**Comment by FlorianLeChat** [comment]
I have just tested the module and it seems that everything works perfectly (at least on Windows and Linux). I didn't test all the functions but only the ones most likely to be used. Thanks a lot for the time you took for this!

I'll leave this issue open just in case if you want to wait for other people's feedback.
